"""empty message

Revision ID: 044382be2f81
Revises: 
Create Date: 2023-03-03 11:52:11.819560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044382be2f81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
