"""empty message

Revision ID: 21b3349856c8
Revises: 044382be2f81
Create Date: 2023-03-03 11:56:08.657105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b3349856c8'
down_revision = '044382be2f81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
