"""empty message

Revision ID: 64cdb4132631
Revises: bee6259d4f3f
Create Date: 2023-03-03 15:30:24.533033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cdb4132631'
down_revision = 'bee6259d4f3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
