"""empty message

Revision ID: 7fe54f784829
Revises: bd3d1c6d3eb1
Create Date: 2023-03-03 12:55:56.810416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe54f784829'
down_revision = 'bd3d1c6d3eb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
