"""empty message

Revision ID: bee6259d4f3f
Revises: 7fe54f784829
Create Date: 2023-03-03 13:08:44.129155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee6259d4f3f'
down_revision = '7fe54f784829'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
